# .streamlit/secrets.toml
mongo_uri = "mongodb+srv://TAK_USER:Arpith%2692@cluster0.ewncl10.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[users]
Arpith = "1234"
Reena  = "5678"
Teena  = "7777"
Kuldeep= "8888"
